### ISSUE TITLE
Crash when going from light to dark

### ISSUE THREAD

**Issue by gunnx** [JoseRFelix/react-toggle-dark-mode#1]
Was getting an error about interpolation failing and after having a look I fixed it by changing the property value for light mask cy

```
defaultProperties: {
  ...
 light: {
    ...,
    mask: {
       cx: '100%',
       cy: '0%'.   <------ This was 0 before 
...
}

**Comment by oalagtash** [comment]
Had the same error. Thx for the hint!

**Comment by JoseRFelix** [comment]
Thanks for bringing up this issue and adding a solution! I have published a fix accordingly :rocket:
