### ISSUE TITLE
inversion prop

### ISSUE THREAD

**Issue by fiorins** [JoseRFelix/react-toggle-dark-mode#20]
Hi, it would be useful to have a prop that allow to choose of invert moon when there is light theme and sun when there is dark theme instead now by default it's the opposite, to do it now we have to modify animationProperties but this is uncomfortable.

**Comment by dogfootruler-kr** [comment]
Hi,

you can do it like that too:
```
<DarkModeSwitch checked={!darkMode} onChange={toggleDarkMode} moonColor='black' sunColor="white" />
```

Set `checked={!darkMode}` and change the sun and moon color.
