### ISSUE TITLE
Cannot animate between AnimatedValue and AnimatedString, as the "to" prop suggests

### ISSUE THREAD

**Issue by acatzk** [JoseRFelix/react-toggle-dark-mode#6]
Unhandled Runtime Error

I am using next.js and when ever i clicked a button error occured

**Comment by JoseRFelix** [comment]
I would love to help you with this, but I need more details about this.

**Comment by acatzk** [comment]
I am using JavaScript and I think the problem is the TypeScript Built in this plugin

const toggleDarkMode = (checked: boolean) => { // type Boolean
    setDarkMode(checked);
  };
